// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-flatten/gulp-flatten.d.ts
declare module "gulp-flatten" {

    interface IOptions {
        newPath: string;
    }

    function flatten(options?: IOptions): NodeJS.ReadWriteStream;

    namespace flatten {}

    export = flatten;
}